from django.contrib.auth import get_user_model
from blog.models import Post,Comment
from random import randint
User = get_user_model()

title = ["Lorem ipsum sunt dolore aute adipisicing pariatur sint minim eiusmod veniam in ut eiusmod proident voluptate laboris magna aliqua dolor."," Culpa ex id commodo cillum occaecat mollit in exercitation fugiat dolor duis."," Ea reprehenderit nisi labore labore duis aute ut non enim nisi exercitation esse nulla deserunt."," Do commodo aliquip excepteur voluptate amet commodo cupidatat adipisicing ex pariatur in elit amet duis nulla consequat quis."," Occaecat anim ea fugiat proident veniam quis veniam ex commodo laboris dolore anim pariatur labore elit est."," Pariatur ea anim labore et aliqua in labore laborum reprehenderit dolore non tempor aute ex."," Nostrud ad pariatur ut consectetur culpa laborum irure minim ut occaecat fugiat enim eu pariatur aute laborum sed."," Sit eiusmod anim qui elit duis labore in culpa cillum in ullamco aliqua enim nisi officia in."," Tempor ut sed occaecat consectetur minim pariatur minim et esse elit eiusmod in adipisicing eu veniam magna."," Nisi incididunt voluptate ut proident laboris officia aliquip sed duis dolore pariatur qui."," In dolore eu irure minim nostrud tempor ad et in incididunt aliqua laboris fugiat."," Lorem ipsum commodo ad anim laboris sint nisi culpa dolor excepteur."," Veniam aliquip commodo nulla occaecat adipisicing officia eiusmod enim officia occaecat adipisicing reprehenderit eu esse."," Lorem ipsum cillum aliqua veniam duis ad quis minim est sit tempor."," Magna voluptate aliquip ut laborum consectetur irure voluptate id et eu irure adipisicing fugiat."," Aliquip anim cupidatat consequat irure anim laboris in enim ex aliquip et quis in magna est reprehenderit est consectetur."," Lorem ipsum nisi quis quis sint aliquip minim tempor et sed irure dolore laborum commodo deserunt velit aliquip ea sunt."]
tags = ["Enim mollit amet dolor dolor veniam"," fugiat dolore adipisicing pariatur","elit dolore cupidatat ullamco ullamco"," Laborum occaecat adipisicing adipisicing nisi sunt laboris eiusmod sint"," Tempor do incididunt dolore est dolor tempor ad magna dolor"," Lorem ipsum irure do enim occaecat excepteur proident sed veniam id reprehenderit amet"," Ex ullamco incididunt adipisicing occaecat labore occaecat veniam cupidatat aliquip"," Veniam aliquip aute excepteur amet minim ","exercitation est laborum dolore ","sit amet irure dolore elit do"]
content = '''Elit fugiat nostrud et minim velit velit aute dolore veniam in elit. Anim labore velit do quis laborum duis eiusmod labore adipisicing dolore id anim ad nisi fugiat duis. Dolore ut excepteur minim in aliquip mollit nostrud ad qui dolore enim nulla labore duis duis. Voluptate nisi incididunt minim sunt eu veniam esse ut consequat quis. Irure ut est ullamco anim aute anim in minim tempor ad quis. Dolore culpa magna commodo consequat commodo et et dolor minim aute aliquip ullamco. Incididunt ex voluptate irure deserunt dolor do mollit dolor in officia id aliquip. Eiusmod dolore nisi in ut excepteur et laborum anim occaecat occaecat occaecat. Officia elit quis enim quis deserunt velit officia laborum adipisicing cillum ea deserunt aliqua ut do mollit dolor in. Ea culpa laborum in in occaecat aliqua non in aliquip culpa magna. Et commodo pariatur aliqua commodo est ex quis duis dolore. Lorem ipsum magna in enim cillum irure ea sit incididunt veniam exercitation reprehenderit ad officia cupidatat labore et consequat dolor dolor. Cillum cupidatat fugiat dolore dolor ut enim id reprehenderit sint dolore labore. Quis reprehenderit culpa ut ex qui ut culpa elit ea cupidatat laboris ut officia ex cupidatat. Sunt proident occaecat cupidatat occaecat ea qui nulla fugiat reprehenderit officia. Ut adipisicing nisi qui proident velit do proident ullamco. Dolore dolore nulla sed aliqua officia ullamco veniam exercitation. Elit proident culpa est aliquip aute amet amet sunt non veniam cillum nostrud occaecat.
Culpa commodo sit incididunt laborum sunt deserunt occaecat ullamco. Eu nisi reprehenderit officia quis ullamco et commodo aliqua eu ex aliquip irure excepteur. Lorem ipsum sint dolor irure anim amet aliquip in in dolor id proident dolore commodo dolore. Dolore minim officia laboris commodo eu mollit dolor cillum anim sint duis. Lorem ipsum excepteur elit eiusmod anim commodo ut aute nisi anim occaecat dolore excepteur ex exercitation eiusmod nisi mollit ex. Laboris sed ullamco in magna exercitation sint ullamco duis velit tempor eiusmod. In enim deserunt ut nostrud culpa ea aute laborum dolor commodo in et sed. Ex dolore laboris ea mollit et ut in ad in esse adipisicing consectetur sunt. Lorem ipsum do duis dolore cupidatat deserunt culpa deserunt non nisi nostrud fugiat nulla enim ut. Ea amet incididunt amet sint excepteur reprehenderit officia non cillum magna commodo esse labore fugiat. Sunt nisi dolor ut id amet excepteur eiusmod quis ea cupidatat labore irure sint fugiat laboris mollit anim. Do irure amet veniam dolor magna qui consequat ad occaecat sunt aliqua dolor laborum voluptate. Non ad amet laborum velit ea velit in commodo consectetur elit cupidatat nisi laborum sed eiusmod labore in. Lorem ipsum sint labore sunt quis occaecat ut laboris in do enim nostrud ea nisi nostrud mollit. Sint cillum velit dolore dolore tempor ea proident in commodo ut deserunt duis do excepteur ut mollit incididunt in. Enim adipisicing reprehenderit ut exercitation tempor est in et sit adipisicing voluptate adipisicing ex ut consectetur. Nisi velit adipisicing laboris minim veniam sed velit sint ut. Et officia ex voluptate incididunt id eu nostrud eu nisi aute ex adipisicing cupidatat consectetur fugiat. Lorem ipsum deserunt enim in velit magna proident nostrud in ex proident excepteur et est tempor. Lorem ipsum dolore laborum anim duis eu mollit ut dolore dolor esse cillum id in deserunt exercitation ex eu aute. Sunt ut nostrud nisi in exercitation aliqua tempor do commodo. Lorem ipsum dolor dolor tempor cillum aliquip minim tempor ut occaecat quis labore. Sed aliquip ut irure tempor cillum in cupidatat ut eu et laboris ullamco dolore qui esse sunt. Lorem ipsum sit dolor aliquip ut ut exercitation proident cillum non dolor esse in duis qui deserunt mollit sunt duis. Officia labore aliquip voluptate aute proident in ea ullamco ea. Cillum qui nulla aute aute mollit quis excepteur sed. Esse dolor ex consequat nulla pariatur sit sed nulla qui incididunt ut dolore. Pariatur tempor ut excepteur cillum aliqua fugiat amet sint id non proident. Aute sed duis dolore sit non esse nostrud non ut aute ea nostrud cillum.
Lorem ipsum exercitation velit nisi dolore amet do consectetur ullamco pariatur occaecat aliquip qui enim duis. Elit deserunt do laborum do dolore labore consequat in reprehenderit nulla culpa eu deserunt eu in dolore. Aute qui eu proident excepteur culpa pariatur elit proident dolore irure tempor laboris.
Nulla in eiusmod excepteur anim in sint incididunt dolor dolor ea id. Dolore proident aliquip culpa velit exercitation enim id incididunt consectetur et do consequat id irure officia dolor. Reprehenderit ut ad deserunt non occaecat sint laboris ex labore ullamco proident mollit reprehenderit aute non officia. Adipisicing esse est nulla ut velit sed eiusmod qui velit in in anim ut sed laboris non aliqua. Culpa amet ex sed do cillum incididunt eu do aliqua. Lorem ipsum aute esse fugiat id et voluptate ea quis anim esse ad.
'''
comments = ["Ut ex commodo incididunt in officia esse excepteur anim ex cupidatat do fugiat cillum aliquip ut."," Esse id pariatur deserunt nostrud laboris mollit ullamco laboris proident anim."," Nisi ut ea adipisicing aute cupidatat laborum aliqua voluptate duis sit quis aliquip ex dolore labore irure sit proident."," Lorem ipsum ullamco labore id tempor labore consequat nisi magna esse ut sint id eiusmod occaecat magna amet."," Quis esse qui velit sed eu sed eiusmod cillum cupidatat ex sint fugiat."," Nisi esse mollit eiusmod ut exercitation duis amet velit."," Eiusmod in ut anim excepteur elit labore in exercitation nisi excepteur adipisicing dolor."," Exercitation et proident laborum ex sint excepteur labore adipisicing duis dolore veniam irure in duis fugiat proident."," Lorem ipsum sit officia occaecat laborum exercitation ea ut in esse laboris ut mollit ea nisi do deserunt."," Proident qui consectetur aute aliqua in sed ut sit sunt dolor consectetur cupidatat anim in voluptate ea labore quis."," Enim in in in enim proident do enim do culpa in cillum ullamco dolor laborum ut dolor."," Nulla qui aliquip dolor ad duis enim ex velit."," Nulla labore reprehenderit dolore ea laboris incididunt enim non."," Sed sint officia mollit cupidatat irure et qui dolore."," Lorem ipsum duis sit dolore proident laboris laboris ut tempor sint pariatur et velit in."," Excepteur consectetur est voluptate et dolor proident in in duis enim do."," Occaecat nostrud quis dolore ullamco ut ut commodo sunt magna sint in voluptate officia ad dolor fugiat anim."," Non ad nulla nulla ea laborum reprehenderit ex ut reprehenderit veniam esse excepteur ut culpa voluptate."," Lorem ipsum ut est reprehenderit minim proident anim amet ea in adipisicing ea ex quis qui mollit ea esse."," Lorem ipsum minim id et ullamco amet dolore tempor eiusmod amet esse do officia sunt dolor deserunt exercitation."," Cupidatat id consectetur mollit ullamco laboris aliqua mollit proident elit excepteur officia elit proident ullamco aliquip enim."," Non ut adipisicing dolore deserunt deserunt anim occaecat qui nostrud aute nostrud deserunt cillum ad irure sed."," Veniam nulla tempor commodo in eiusmod do tempor cupidatat irure nisi."]


def generate_dummy_post(n):
	for i in range(n):
		a = Post()
		a.title = title[randint(0, len(title)-1)][:80]
		a.tags = tags[randint(0, len(tags)-1)].strip().replace(" ", ",")
		a.content = content
		a.author = User.objects.get(pk=randint(1, len(User.objects.all())))
		a.save()


def generate_dummy_comment():
	for p in Post.objects.all():
		for u in User.objects.all():
			p.comment_set.create(author=u,text=comments[randint(0, len(comments)-1)])
		p.save()