# Generated by Django 3.1.4 on 2021-01-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210101_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
